spring.application.name=AbhiKharidoo


spring.datasource.url= jdbc:postgresql://localhost:5432/abhishek
spring.datasource.username=abhishek
spring.datasource.password=Abhi@1234

spring.jpa.hibernate.ddl-auto=update